import { AnimalSpecies, AnimalSpeciesInfo } from './types';

export const FAUNA_DATABASE: Record<string, AnimalSpeciesInfo> = {
  [AnimalSpecies.CHEETAH]: {
    id: AnimalSpecies.CHEETAH,
    name: 'Cheetah',
    scientificName: 'Acinonyx jubatus',
    family: 'Felidae',
    nativeRange: 'Africa & Iran',
    notes: 'Fastest land animal, capable of 0-60 mph in three seconds.',
    diet: 'carnivore',
    maxHealth: 100,
    speed: 1.0,
    strength: 0.6,
    intelligence: 0.7,
    lifespan: 12,
    gestationPeriod: 90
  },
  [AnimalSpecies.PANDA]: {
    id: AnimalSpecies.PANDA,
    name: 'Giant Panda',
    scientificName: 'Ailuropoda melanoleuca',
    family: 'Ursidae',
    nativeRange: 'China',
    notes: 'Primarily herbivorous bear that eats almost exclusively bamboo.',
    diet: 'herbivore',
    maxHealth: 150,
    speed: 0.3,
    strength: 0.8,
    intelligence: 0.6,
    lifespan: 20,
    gestationPeriod: 135
  },
  [AnimalSpecies.MOOSE]: {
    id: AnimalSpecies.MOOSE,
    name: 'Moose',
    scientificName: 'Alces alces',
    family: 'Cervidae',
    nativeRange: 'North America & Eurasia',
    notes: 'Largest living deer species; males have distinctive palmate antlers.',
    diet: 'herbivore',
    maxHealth: 250,
    speed: 0.5,
    strength: 0.9,
    intelligence: 0.5,
    lifespan: 15,
    gestationPeriod: 240
  },
  [AnimalSpecies.CLOWNFISH]: {
    id: AnimalSpecies.CLOWNFISH,
    name: 'Clownfish',
    scientificName: 'Amphiprion ocellaris',
    family: 'Pomacentridae',
    nativeRange: 'Indo-Pacific',
    notes: 'Forms symbiotic mutualism with sea anemones; all are born male.',
    diet: 'omnivore',
    maxHealth: 20,
    speed: 0.4,
    strength: 0.1,
    intelligence: 0.4,
    lifespan: 6,
    gestationPeriod: 10
  },
  [AnimalSpecies.DRAGONFLY]: {
    id: AnimalSpecies.DRAGONFLY,
    name: 'Emperor Dragonfly',
    scientificName: 'Anax imperator',
    family: 'Aeshnidae',
    nativeRange: 'Europe, Africa & Asia',
    notes: 'One of the largest dragonflies; hunts other insects in flight.',
    diet: 'carnivore',
    maxHealth: 10,
    speed: 0.8,
    strength: 0.2,
    intelligence: 0.3,
    lifespan: 1,
    gestationPeriod: 7
  },
  [AnimalSpecies.HONEY_BEE]: {
    id: AnimalSpecies.HONEY_BEE,
    name: 'Western Honey Bee',
    scientificName: 'Apis mellifera',
    family: 'Apidae',
    nativeRange: 'Africa & Eurasia',
    notes: 'Produces honey and beeswax; lives in highly organized colonies.',
    diet: 'herbivore',
    maxHealth: 5,
    speed: 0.6,
    strength: 0.1,
    intelligence: 0.8,
    lifespan: 0.5,
    gestationPeriod: 3
  },
  [AnimalSpecies.GOLDEN_EAGLE]: {
    id: AnimalSpecies.GOLDEN_EAGLE,
    name: 'Golden Eagle',
    scientificName: 'Aquila chrysaetos',
    family: 'Accipitridae',
    nativeRange: 'Holarctic',
    notes: 'One of the largest and fastest raptors; used in falconry for centuries.',
    diet: 'carnivore',
    maxHealth: 80,
    speed: 0.9,
    strength: 0.7,
    intelligence: 0.8,
    lifespan: 25,
    gestationPeriod: 45
  },
  [AnimalSpecies.GIANT_SQUID]: {
    id: AnimalSpecies.GIANT_SQUID,
    name: 'Giant Squid',
    scientificName: 'Architeuthis dux',
    family: 'Architeuthidae',
    nativeRange: 'Deep oceans worldwide',
    notes: 'Elusive deep-sea squid; has the largest eyes of any known animal.',
    diet: 'carnivore',
    maxHealth: 300,
    speed: 0.6,
    strength: 0.9,
    intelligence: 0.7,
    lifespan: 5,
    gestationPeriod: 30
  },
  [AnimalSpecies.BLUE_WHALE]: {
    id: AnimalSpecies.BLUE_WHALE,
    name: 'Blue Whale',
    scientificName: 'Balaenoptera musculus',
    family: 'Balaenopteridae',
    nativeRange: 'Worldwide oceans',
    notes: 'Largest animal ever known to have existed (up to 30 meters long).',
    diet: 'carnivore',
    maxHealth: 1000,
    speed: 0.4,
    strength: 1.0,
    intelligence: 0.8,
    lifespan: 80,
    gestationPeriod: 365
  },
  [AnimalSpecies.BISON]: {
    id: AnimalSpecies.BISON,
    name: 'American Bison',
    scientificName: 'Bison bison',
    family: 'Bovidae',
    nativeRange: 'North America',
    notes: 'National mammal of the US; once roamed in vast herds of millions.',
    diet: 'herbivore',
    maxHealth: 400,
    speed: 0.4,
    strength: 0.9,
    intelligence: 0.5,
    lifespan: 20,
    gestationPeriod: 285
  },
  [AnimalSpecies.BUMBLEBEE]: {
    id: AnimalSpecies.BUMBLEBEE,
    name: 'Buff-tailed Bumblebee',
    scientificName: 'Bombus terrestris',
    family: 'Apidae',
    nativeRange: 'Europe & Asia',
    notes: 'Important pollinator; can vibrate its body to release pollen from flowers.',
    diet: 'herbivore',
    maxHealth: 5,
    speed: 0.5,
    strength: 0.1,
    intelligence: 0.7,
    lifespan: 0.5,
    gestationPeriod: 3
  },
  [AnimalSpecies.CATTLE]: {
    id: AnimalSpecies.CATTLE,
    name: 'Cattle',
    scientificName: 'Bos taurus',
    family: 'Bovidae',
    nativeRange: 'Worldwide (domesticated)',
    notes: 'Domesticated from aurochs; provides milk, meat, leather, and draft power.',
    diet: 'herbivore',
    maxHealth: 300,
    speed: 0.3,
    strength: 0.8,
    intelligence: 0.4,
    lifespan: 20,
    gestationPeriod: 280,
    isDomesticated: true
  },
  [AnimalSpecies.OWL]: {
    id: AnimalSpecies.OWL,
    name: 'Great Horned Owl',
    scientificName: 'Bubo virginianus',
    family: 'Strigidae',
    nativeRange: 'Americas',
    notes: 'Powerful predator with distinctive ear tufts; takes prey larger than itself.',
    diet: 'carnivore',
    maxHealth: 60,
    speed: 0.7,
    strength: 0.6,
    intelligence: 0.8,
    lifespan: 15,
    gestationPeriod: 30
  },
  [AnimalSpecies.DROMEDARY]: {
    id: AnimalSpecies.DROMEDARY,
    name: 'Dromedary Camel',
    scientificName: 'Camelus dromedarius',
    family: 'Camelidae',
    nativeRange: 'Middle East & Africa',
    notes: 'Single hump stores fat; can go days without water in hot deserts.',
    diet: 'herbivore',
    maxHealth: 250,
    speed: 0.4,
    strength: 0.7,
    intelligence: 0.6,
    lifespan: 40,
    gestationPeriod: 390
  },
  [AnimalSpecies.GRAY_WOLF]: {
    id: AnimalSpecies.GRAY_WOLF,
    name: 'Gray Wolf',
    scientificName: 'Canis lupus',
    family: 'Candidae',
    nativeRange: 'Eurasia & North America',
    notes: 'Ancestor of the domestic dog; lives and hunts in packs.',
    diet: 'carnivore',
    maxHealth: 100,
    speed: 0.7,
    strength: 0.7,
    intelligence: 0.9,
    lifespan: 12,
    gestationPeriod: 63
  },
  [AnimalSpecies.GOAT]: {
    id: AnimalSpecies.GOAT,
    name: 'Goat',
    scientificName: 'Capra hircus',
    family: 'Bovidae',
    nativeRange: 'Asia (wild Bezoar ibex)',
    notes: 'Domesticated for milk, meat, fiber (mohair, cashmere), and leather.',
    diet: 'herbivore',
    maxHealth: 80,
    speed: 0.5,
    strength: 0.5,
    intelligence: 0.7,
    lifespan: 15,
    gestationPeriod: 150,
    isDomesticated: true
  },
  [AnimalSpecies.SEA_TURTLE]: {
    id: AnimalSpecies.SEA_TURTLE,
    name: 'Green Sea Turtle',
    scientificName: 'Chelonia mydas',
    family: 'Cheloniidae',
    nativeRange: 'Tropical & subtropical oceans',
    notes: 'Herbivorous sea turtle named for green body fat; endangered.',
    diet: 'herbivore',
    maxHealth: 150,
    speed: 0.3,
    strength: 0.6,
    intelligence: 0.5,
    lifespan: 80,
    gestationPeriod: 60
  },
  [AnimalSpecies.PHEASANT]: {
    id: AnimalSpecies.PHEASANT,
    name: 'Golden Pheasant',
    scientificName: 'Chrysolophus pictus',
    family: 'Phasianidae',
    nativeRange: 'Western China',
    notes: 'Strikingly colorful bird with a golden crest and long tail.',
    diet: 'omnivore',
    maxHealth: 30,
    speed: 0.5,
    strength: 0.2,
    intelligence: 0.4,
    lifespan: 10,
    gestationPeriod: 22
  },
  [AnimalSpecies.PIGEON]: {
    id: AnimalSpecies.PIGEON,
    name: 'Rock Dove (Pigeon)',
    scientificName: 'Columba livia',
    family: 'Columbidae',
    nativeRange: 'Europe, Africa & Asia',
    notes: 'Domesticated thousands of years ago; used as carrier pigeons in wars.',
    diet: 'herbivore',
    maxHealth: 20,
    speed: 0.6,
    strength: 0.2,
    intelligence: 0.7,
    lifespan: 10,
    gestationPeriod: 18,
    isDomesticated: true
  },
  [AnimalSpecies.RAVEN]: {
    id: AnimalSpecies.RAVEN,
    name: 'Common Raven',
    scientificName: 'Corvus corax',
    family: 'Corvidae',
    nativeRange: 'Holarctic',
    notes: 'Highly intelligent; known to use tools, solve puzzles, and mimic sounds.',
    diet: 'omnivore',
    maxHealth: 40,
    speed: 0.7,
    strength: 0.3,
    intelligence: 1.0,
    lifespan: 15,
    gestationPeriod: 20
  },
  [AnimalSpecies.SALTWATER_CROCODILE]: {
    id: AnimalSpecies.SALTWATER_CROCODILE,
    name: 'Saltwater Crocodile',
    scientificName: 'Crocodylus porosus',
    family: 'Crocodylidae',
    nativeRange: 'Indo-Pacific',
    notes: 'Largest living reptile; powerful bite and tolerates salt water.',
    diet: 'carnivore',
    maxHealth: 400,
    speed: 0.4,
    strength: 1.0,
    intelligence: 0.6,
    lifespan: 70,
    gestationPeriod: 80
  },
  [AnimalSpecies.MONARCH_BUTTERFLY]: {
    id: AnimalSpecies.MONARCH_BUTTERFLY,
    name: 'Monarch Butterfly',
    scientificName: 'Danaus plexippus',
    family: 'Nymphalidae',
    nativeRange: 'North America',
    notes: 'Famous for long-distance migration (up to 4,000 km) to Mexico.',
    diet: 'herbivore',
    maxHealth: 5,
    speed: 0.4,
    strength: 0.1,
    intelligence: 0.3,
    lifespan: 0.5,
    gestationPeriod: 10
  },
  [AnimalSpecies.DOLPHIN]: {
    id: AnimalSpecies.DOLPHIN,
    name: 'Short-beaked Common Dolphin',
    scientificName: 'Delphinus delphis',
    family: 'Delphinidae',
    nativeRange: 'Temperate & tropical oceans',
    notes: 'Highly social and acrobatic; often rides bow waves of boats.',
    diet: 'carnivore',
    maxHealth: 150,
    speed: 0.8,
    strength: 0.7,
    intelligence: 0.9,
    lifespan: 30,
    gestationPeriod: 330
  },
  [AnimalSpecies.FRUIT_FLY]: {
    id: AnimalSpecies.FRUIT_FLY,
    name: 'Fruit Fly',
    scientificName: 'Drosophila melanogaster',
    family: 'Drosophilidae',
    nativeRange: 'Worldwide',
    notes: 'Model organism in genetics; has a short life cycle of about 10 days.',
    diet: 'herbivore',
    maxHealth: 2,
    speed: 0.3,
    strength: 0.05,
    intelligence: 0.2,
    lifespan: 0.1,
    gestationPeriod: 1
  },
  [AnimalSpecies.ECHIDNA]: {
    id: AnimalSpecies.ECHIDNA,
    name: 'Short-beaked Echidna',
    scientificName: 'Echidna (Tachyglossus aculeatus)',
    family: 'Tachyglossidae',
    nativeRange: 'Australia & New Guinea',
    notes: 'One of only two monotremes (egg-laying mammals); males have a four-headed penis.',
    diet: 'carnivore',
    maxHealth: 60,
    speed: 0.3,
    strength: 0.4,
    intelligence: 0.5,
    lifespan: 40,
    gestationPeriod: 10
  },
  [AnimalSpecies.ASIAN_ELEPHANT]: {
    id: AnimalSpecies.ASIAN_ELEPHANT,
    name: 'Asian Elephant',
    scientificName: 'Elephas maximus',
    family: 'Elephantidae',
    nativeRange: 'South & Southeast Asia',
    notes: 'Smaller ears than African elephant; highly intelligent and social.',
    diet: 'herbivore',
    maxHealth: 500,
    speed: 0.4,
    strength: 1.0,
    intelligence: 0.9,
    lifespan: 60,
    gestationPeriod: 640
  },
  [AnimalSpecies.HORSE]: {
    id: AnimalSpecies.HORSE,
    name: 'Horse',
    scientificName: 'Equus ferus caballus',
    family: 'Equidae',
    nativeRange: 'Worldwide (domesticated)',
    notes: 'Domesticated from wild horses; used for transport, agriculture, and sport.',
    diet: 'herbivore',
    maxHealth: 300,
    speed: 0.8,
    strength: 0.8,
    intelligence: 0.7,
    lifespan: 25,
    gestationPeriod: 330,
    isDomesticated: true
  },
  [AnimalSpecies.PEREGRINE_FALCON]: {
    id: AnimalSpecies.PEREGRINE_FALCON,
    name: 'Peregrine Falcon',
    scientificName: 'Falco peregrinus',
    family: 'Falconidae',
    nativeRange: 'Worldwide',
    notes: 'Fastest animal on Earth; can exceed 320 km/h (200 mph) in a dive.',
    diet: 'carnivore',
    maxHealth: 50,
    speed: 1.0,
    strength: 0.5,
    intelligence: 0.8,
    lifespan: 15,
    gestationPeriod: 33
  },
  [AnimalSpecies.CAT]: {
    id: AnimalSpecies.CAT,
    name: 'Domestic Cat',
    scientificName: 'Felis catus',
    family: 'Felidae',
    nativeRange: 'Worldwide (domesticated)',
    notes: 'Descended from African wildcat; one of the most popular pets globally.',
    diet: 'carnivore',
    maxHealth: 40,
    speed: 0.7,
    strength: 0.3,
    intelligence: 0.8,
    lifespan: 15,
    gestationPeriod: 65,
    isDomesticated: true
  },
  [AnimalSpecies.CHAFFINCH]: {
    id: AnimalSpecies.CHAFFINCH,
    name: 'Common Chaffinch',
    scientificName: 'Fringilla coelebs',
    family: 'Fringillidae',
    nativeRange: 'Europe & Asia',
    notes: 'Common garden bird with a cheerful song; males have blue-grey caps.',
    diet: 'omnivore',
    maxHealth: 15,
    speed: 0.5,
    strength: 0.1,
    intelligence: 0.5,
    lifespan: 5,
    gestationPeriod: 14
  },
  [AnimalSpecies.GECKO]: {
    id: AnimalSpecies.GECKO,
    name: 'Tokay Gecko',
    scientificName: 'Gekko gecko',
    family: 'Gekkonidae',
    nativeRange: 'South & Southeast Asia',
    notes: 'Large, colorful gecko known for its loud "to-kay" call.',
    diet: 'carnivore',
    maxHealth: 25,
    speed: 0.4,
    strength: 0.2,
    intelligence: 0.4,
    lifespan: 10,
    gestationPeriod: 60
  },
  [AnimalSpecies.GIRAFFE]: {
    id: AnimalSpecies.GIRAFFE,
    name: 'Giraffe',
    scientificName: 'Giraffa camelopardalis',
    family: 'Giraffidae',
    nativeRange: 'Africa',
    notes: 'Tallest land animal; long neck and tongue for browsing acacia trees.',
    diet: 'herbivore',
    maxHealth: 400,
    speed: 0.6,
    strength: 0.8,
    intelligence: 0.6,
    lifespan: 25,
    gestationPeriod: 450
  },
  [AnimalSpecies.SNAIL]: {
    id: AnimalSpecies.SNAIL,
    name: 'Roman Snail',
    scientificName: 'Helix pomatia',
    family: 'Helicidae',
    nativeRange: 'Europe',
    notes: 'Edible snail; used in classic French dish escargot de Bourgogne.',
    diet: 'herbivore',
    maxHealth: 5,
    speed: 0.05,
    strength: 0.05,
    intelligence: 0.1,
    lifespan: 5,
    gestationPeriod: 20
  },
  [AnimalSpecies.HUMAN_SPECIES]: {
    id: AnimalSpecies.HUMAN_SPECIES,
    name: 'Human',
    scientificName: 'Homo sapiens',
    family: 'Hominidae',
    nativeRange: 'Worldwide',
    notes: 'Only living species in the genus Homo; highly advanced tool use and language.',
    diet: 'omnivore',
    maxHealth: 100,
    speed: 0.5,
    strength: 0.6,
    intelligence: 1.0,
    lifespan: 80,
    gestationPeriod: 270
  },
  [AnimalSpecies.AFRICAN_ELEPHANT]: {
    id: AnimalSpecies.AFRICAN_ELEPHANT,
    name: 'African Bush Elephant',
    scientificName: 'Loxodonta africana',
    family: 'Elephantidae',
    nativeRange: 'Africa',
    notes: 'Largest living land animal; both sexes have tusks and large ears.',
    diet: 'herbivore',
    maxHealth: 600,
    speed: 0.4,
    strength: 1.0,
    intelligence: 0.9,
    lifespan: 70,
    gestationPeriod: 660
  },
  [AnimalSpecies.OTTER]: {
    id: AnimalSpecies.OTTER,
    name: 'Eurasian Otter',
    scientificName: 'Lutra lutra',
    family: 'Mustelidae',
    nativeRange: 'Europe & Asia',
    notes: 'Semi-aquatic predator; uses whiskers to detect prey in murky water.',
    diet: 'carnivore',
    maxHealth: 60,
    speed: 0.6,
    strength: 0.5,
    intelligence: 0.8,
    lifespan: 12,
    gestationPeriod: 60
  },
  [AnimalSpecies.KANGAROO]: {
    id: AnimalSpecies.KANGAROO,
    name: 'Eastern Grey Kangaroo',
    scientificName: 'Macropus giganteus',
    family: 'Macropodidae',
    nativeRange: 'Eastern Australia',
    notes: 'Large marsupial; can hop at 40 mph and leap 9 meters in a single bound.',
    diet: 'herbivore',
    maxHealth: 120,
    speed: 0.8,
    strength: 0.7,
    intelligence: 0.6,
    lifespan: 15,
    gestationPeriod: 36
  },
  [AnimalSpecies.EUROPEAN_RABBIT]: {
    id: AnimalSpecies.EUROPEAN_RABBIT,
    name: 'European Rabbit',
    scientificName: 'Oryctolagus cuniculus',
    family: 'Leporidae',
    nativeRange: 'Iberian Peninsula',
    notes: 'Ancestor of all domestic rabbits; known for rapid breeding.',
    diet: 'herbivore',
    maxHealth: 30,
    speed: 0.7,
    strength: 0.2,
    intelligence: 0.5,
    lifespan: 8,
    gestationPeriod: 30
  },
  [AnimalSpecies.LION]: {
    id: AnimalSpecies.LION,
    name: 'Lion',
    scientificName: 'Panthera leo',
    family: 'Felidae',
    nativeRange: 'Africa & small population in India',
    notes: 'Only social cat species; females do most of the hunting.',
    diet: 'carnivore',
    maxHealth: 250,
    speed: 0.7,
    strength: 0.9,
    intelligence: 0.8,
    lifespan: 15,
    gestationPeriod: 110
  },
  [AnimalSpecies.TIGER]: {
    id: AnimalSpecies.TIGER,
    name: 'Tiger',
    scientificName: 'Panthera tigris',
    family: 'Asia',
    nativeRange: 'Asia',
    notes: 'Largest wild cat; distinctive orange coat with black stripes.',
    diet: 'carnivore',
    maxHealth: 300,
    speed: 0.7,
    strength: 1.0,
    intelligence: 0.8,
    lifespan: 15,
    gestationPeriod: 105
  },
  [AnimalSpecies.SWALLOWTAIL]: {
    id: AnimalSpecies.SWALLOWTAIL,
    name: 'Old World Swallowtail',
    scientificName: 'Papilio machaon',
    family: 'Papilionidae',
    nativeRange: 'Eurasia & North America',
    notes: 'Large, striking butterfly with tail-like extensions on hindwings.',
    diet: 'herbivore',
    maxHealth: 5,
    speed: 0.4,
    strength: 0.1,
    intelligence: 0.3,
    lifespan: 0.5,
    gestationPeriod: 10
  },
  [AnimalSpecies.GREAT_TIT]: {
    id: AnimalSpecies.GREAT_TIT,
    name: 'Great Tit',
    scientificName: 'Parus major',
    family: 'Paridae',
    nativeRange: 'Europe & Asia',
    notes: 'Common garden bird; known for its ability to learn and problem-solve.',
    diet: 'omnivore',
    maxHealth: 15,
    speed: 0.5,
    strength: 0.1,
    intelligence: 0.8,
    lifespan: 5,
    gestationPeriod: 14
  },
  [AnimalSpecies.SPARROW]: {
    id: AnimalSpecies.SPARROW,
    name: 'House Sparrow',
    scientificName: 'Passer domesticus',
    family: 'Passeridae',
    nativeRange: 'Europe & Asia',
    notes: 'One of the most widespread birds; closely associated with human habitation.',
    diet: 'omnivore',
    maxHealth: 15,
    speed: 0.5,
    strength: 0.1,
    intelligence: 0.6,
    lifespan: 5,
    gestationPeriod: 12
  },
  [AnimalSpecies.KOALA]: {
    id: AnimalSpecies.KOALA,
    name: 'Koala',
    scientificName: 'Phascolarctos cinereus',
    family: 'Phascolarctidae',
    nativeRange: 'Australia',
    notes: 'Marsupial that eats only eucalyptus leaves; sleeps up to 20 hours daily.',
    diet: 'herbivore',
    maxHealth: 80,
    speed: 0.2,
    strength: 0.4,
    intelligence: 0.4,
    lifespan: 15,
    gestationPeriod: 35
  },
  [AnimalSpecies.ORANGUTAN]: {
    id: AnimalSpecies.ORANGUTAN,
    name: 'Bornean Orangutan',
    scientificName: 'Pongo pygmaeus',
    family: 'Hominidae',
    nativeRange: 'Borneo',
    notes: 'One of the great apes; highly intelligent and primarily arboreal.',
    diet: 'omnivore',
    maxHealth: 180,
    speed: 0.4,
    strength: 0.8,
    intelligence: 0.9,
    lifespan: 40,
    gestationPeriod: 260
  },
  [AnimalSpecies.FROG]: {
    id: AnimalSpecies.FROG,
    name: 'Common Frog',
    scientificName: 'Rana temporaria',
    family: 'Ranidae',
    nativeRange: 'Europe & Asia',
    notes: 'One of the most widespread European frogs; hibernates in mud.',
    diet: 'carnivore',
    maxHealth: 15,
    speed: 0.3,
    strength: 0.1,
    intelligence: 0.3,
    lifespan: 8,
    gestationPeriod: 30
  },
  [AnimalSpecies.RAT]: {
    id: AnimalSpecies.RAT,
    name: 'Brown Rat',
    scientificName: 'Rattus norvegicus',
    family: 'Muridae',
    nativeRange: 'China & Mongolia',
    notes: 'One of the most successful mammals; lives in close association with humans.',
    diet: 'omnivore',
    maxHealth: 20,
    speed: 0.5,
    strength: 0.2,
    intelligence: 0.8,
    lifespan: 3,
    gestationPeriod: 22
  },
  [AnimalSpecies.PENGUIN]: {
    id: AnimalSpecies.PENGUIN,
    name: 'African Penguin',
    scientificName: 'Spheniscus demersus',
    family: 'Spheniscidae',
    nativeRange: 'South Africa',
    notes: 'Only penguin species breeding in Africa; makes donkey-like braying call.',
    diet: 'carnivore',
    maxHealth: 40,
    speed: 0.4,
    strength: 0.3,
    intelligence: 0.6,
    lifespan: 15,
    gestationPeriod: 40
  },
  [AnimalSpecies.OSTRICH]: {
    id: AnimalSpecies.OSTRICH,
    name: 'Ostrich',
    scientificName: 'Struthio camelus',
    family: 'Struthionidae',
    nativeRange: 'Africa',
    notes: 'Largest living bird; lays the largest eggs and cannot fly.',
    diet: 'omnivore',
    maxHealth: 200,
    speed: 0.9,
    strength: 0.8,
    intelligence: 0.5,
    lifespan: 40,
    gestationPeriod: 42
  },
  [AnimalSpecies.BOTTLENOSE_DOLPHIN]: {
    id: AnimalSpecies.BOTTLENOSE_DOLPHIN,
    name: 'Bottlenose Dolphin',
    scientificName: 'Tursiops truncatus',
    family: 'Delphinidae',
    nativeRange: 'Worldwide',
    notes: 'Highly intelligent; known for complex social behavior and tool use.',
    diet: 'carnivore',
    maxHealth: 200,
    speed: 0.8,
    strength: 0.8,
    intelligence: 1.0,
    lifespan: 40,
    gestationPeriod: 365
  },
  [AnimalSpecies.BROWN_BEAR]: {
    id: AnimalSpecies.BROWN_BEAR,
    name: 'Brown Bear',
    scientificName: 'Ursus arctos',
    family: 'Ursidae',
    nativeRange: 'Northern Hemisphere',
    notes: 'Includes the grizzly and Kodiak bear; hibernates through winter.',
    diet: 'omnivore',
    maxHealth: 400,
    speed: 0.6,
    strength: 1.0,
    intelligence: 0.8,
    lifespan: 25,
    gestationPeriod: 210
  },
  [AnimalSpecies.KOMODO_DRAGON]: {
    id: AnimalSpecies.KOMODO_DRAGON,
    name: 'Komodo Dragon',
    scientificName: 'Varanus komodoensis',
    family: 'Varanidae',
    nativeRange: 'Indonesia',
    notes: 'Largest living lizard; has venomous bite and hunts large prey.',
    diet: 'carnivore',
    maxHealth: 200,
    speed: 0.5,
    strength: 0.9,
    intelligence: 0.6,
    lifespan: 30,
    gestationPeriod: 240
  },
  [AnimalSpecies.RED_FOX]: {
    id: AnimalSpecies.RED_FOX,
    name: 'Red Fox',
    scientificName: 'Vulpes vulpes',
    family: 'Canidae',
    nativeRange: 'Northern Hemisphere',
    notes: 'Most widespread wild canid; adaptable to urban environments.',
    diet: 'omnivore',
    maxHealth: 60,
    speed: 0.7,
    strength: 0.4,
    intelligence: 0.9,
    lifespan: 5,
    gestationPeriod: 52
  },
  [AnimalSpecies.CLAWED_FROG]: {
    id: AnimalSpecies.CLAWED_FROG,
    name: 'African Clawed Frog',
    scientificName: 'Xenopus laevis',
    family: 'Pipidae',
    nativeRange: 'Sub-Saharan Africa',
    notes: 'Fully aquatic frog; once used in human pregnancy tests.',
    diet: 'carnivore',
    maxHealth: 20,
    speed: 0.3,
    strength: 0.1,
    intelligence: 0.3,
    lifespan: 15,
    gestationPeriod: 30
  },
  [AnimalSpecies.CRAB]: {
    id: AnimalSpecies.CRAB,
    name: 'Red Crab',
    scientificName: 'Gecarcoidea natalis',
    family: 'Gecarcinidae',
    nativeRange: 'Christmas Island',
    notes: 'Famous for their mass annual migration to the sea to spawn.',
    diet: 'omnivore',
    maxHealth: 15,
    speed: 0.1,
    strength: 0.1,
    intelligence: 0.2,
    lifespan: 12,
    gestationPeriod: 30
  },
  [AnimalSpecies.SEAGULL]: {
    id: AnimalSpecies.SEAGULL,
    name: 'Seagull',
    scientificName: 'Larus',
    family: 'Laridae',
    nativeRange: 'Worldwide',
    notes: 'Highly adaptable coastal birds known for their loud calls.',
    diet: 'omnivore',
    maxHealth: 25,
    speed: 0.7,
    strength: 0.2,
    intelligence: 0.5,
    lifespan: 15,
    gestationPeriod: 25
  }
};
