import { PlantSpecies } from './plants';

export const FLORA_DATABASE: Record<string, PlantSpecies> = {
  'abies_magnifica': {
    id: 'abies_magnifica',
    name: 'California Red Fir',
    scientificName: 'Abies magnifica',
    family: 'Pinaceae',
    nativeRange: 'Western USA',
    notes: 'A true fir species with excellent wood properties.',
    growthRate: 0.08,
    waterNeed: 0.4,
    tempTolerance: [-10, 25],
    hazardResistance: 0.5,
    isPoisonous: false,
    isRare: false,
    woodQuality: 0.9
  },
  'abronia_latifolia': {
    id: 'abronia_latifolia',
    name: 'Yellow Sand Verbena',
    scientificName: 'Abronia latifolia',
    family: 'Nyctaginaceae',
    nativeRange: 'Western North America',
    notes: 'A coastal dune plant with yellow flowers and fleshy leaves.',
    growthRate: 0.3,
    waterNeed: 0.2,
    tempTolerance: [5, 30],
    hazardResistance: 0.7,
    isPoisonous: false,
    isRare: false
  },
  'acacia_koa': {
    id: 'acacia_koa',
    name: 'Koa',
    scientificName: 'Acacia koa',
    family: 'Fabaceae',
    nativeRange: 'Hawaii',
    notes: 'A large tree endemic to Hawaii, prized for its wood.',
    growthRate: 0.12,
    waterNeed: 0.6,
    tempTolerance: [15, 30],
    hazardResistance: 0.4,
    isPoisonous: false,
    isRare: true,
    woodQuality: 1.0
  },
  'acer_saccharum': {
    id: 'acer_saccharum',
    name: 'Sugar Maple',
    scientificName: 'Acer saccharum',
    family: 'Sapindaceae',
    nativeRange: 'Eastern North America',
    notes: 'Known for its vibrant fall color and as the primary source of maple syrup.',
    growthRate: 0.1,
    waterNeed: 0.5,
    tempTolerance: [-5, 28],
    hazardResistance: 0.3,
    isPoisonous: false,
    isRare: false,
    nutritionalValue: 0.6
  },
  'actaea_racemosa': {
    id: 'actaea_racemosa',
    name: 'Black Cohosh',
    scientificName: 'Actaea racemosa',
    family: 'Ranunculaceae',
    nativeRange: 'Eastern North America',
    notes: 'A herbaceous perennial used in traditional medicine.',
    growthRate: 0.2,
    waterNeed: 0.5,
    tempTolerance: [5, 25],
    hazardResistance: 0.4,
    isPoisonous: false,
    isRare: false,
    medicinalValue: 0.8
  },
  'adansonia_grandidieri': {
    id: 'adansonia_grandidieri',
    name: "Grandidier's Baobab",
    scientificName: 'Adansonia grandidieri',
    family: 'Malvaceae',
    nativeRange: 'Madagascar',
    notes: 'One of the largest trees in the world, storing water in its massive trunk.',
    growthRate: 0.05,
    waterNeed: 0.1,
    tempTolerance: [15, 45],
    hazardResistance: 0.8,
    isPoisonous: false,
    isRare: true,
    nutritionalValue: 0.4
  },
  'agave_americana': {
    id: 'agave_americana',
    name: 'Century Plant',
    scientificName: 'Agave americana',
    family: 'Asparagaceae',
    nativeRange: 'Americas',
    notes: 'A rosette-forming succulent that blooms only once after many years.',
    growthRate: 0.02,
    waterNeed: 0.05,
    tempTolerance: [0, 45],
    hazardResistance: 0.9,
    isPoisonous: false,
    isRare: false,
    nutritionalValue: 0.3
  },
  'allium_sativum': {
    id: 'allium_sativum',
    name: 'Garlic',
    scientificName: 'Allium sativum',
    family: 'Amaryllidaceae',
    nativeRange: 'Central Asia',
    notes: 'A bulbous plant widely used as a culinary spice.',
    growthRate: 0.4,
    waterNeed: 0.3,
    tempTolerance: [5, 30],
    hazardResistance: 0.5,
    isPoisonous: false,
    isRare: false,
    medicinalValue: 0.6,
    nutritionalValue: 0.5
  },
  'aloe_barbadensis': {
    id: 'aloe_barbadensis',
    name: 'Aloe Vera',
    scientificName: 'Aloe barbadensis',
    family: 'Asphodelaceae',
    nativeRange: 'Arabian Peninsula',
    notes: 'A stemless succulent valued for its medicinal and cosmetic gel.',
    growthRate: 0.15,
    waterNeed: 0.1,
    tempTolerance: [10, 40],
    hazardResistance: 0.8,
    isPoisonous: false,
    isRare: false,
    medicinalValue: 0.9
  },
  'amaranthus_caudatus': {
    id: 'amaranthus_caudatus',
    name: 'Love-Lies-Bleeding',
    scientificName: 'Amaranthus caudatus',
    family: 'Amaranthaceae',
    nativeRange: 'South America',
    notes: 'An ornamental plant with striking, long, drooping red flower clusters.',
    growthRate: 0.5,
    waterNeed: 0.4,
    tempTolerance: [15, 35],
    hazardResistance: 0.3,
    isPoisonous: false,
    isRare: false,
    nutritionalValue: 0.7
  },
  'ambrosia_artemisiifolia': {
    id: 'ambrosia_artemisiifolia',
    name: 'Ragweed',
    scientificName: 'Ambrosia artemisiifolia',
    family: 'Asteraceae',
    nativeRange: 'Americas',
    notes: 'A common plant whose pollen is a major cause of hay fever.',
    growthRate: 0.7,
    waterNeed: 0.3,
    tempTolerance: [5, 40],
    hazardResistance: 0.2,
    isPoisonous: false,
    isRare: false
  },
  'amorphophallus_titanum': {
    id: 'amorphophallus_titanum',
    name: 'Titan Arum',
    scientificName: 'Amorphophallus titanum',
    family: 'Araceae',
    nativeRange: 'Sumatra',
    notes: 'Produces the world\'s largest unbranched inflorescence, known for its foul odor.',
    growthRate: 0.01,
    waterNeed: 0.8,
    tempTolerance: [20, 35],
    hazardResistance: 0.4,
    isPoisonous: true,
    isRare: true
  },
  'ananas_comosus': {
    id: 'ananas_comosus',
    name: 'Pineapple',
    scientificName: 'Ananas comosus',
    family: 'Bromeliaceae',
    nativeRange: 'South America',
    notes: 'A terrestrial bromeliad cultivated for its sweet, compound fruit.',
    growthRate: 0.2,
    waterNeed: 0.3,
    tempTolerance: [15, 35],
    hazardResistance: 0.6,
    isPoisonous: false,
    isRare: false,
    nutritionalValue: 0.8
  },
  'andropogon_glomeratus': {
    id: 'andropogon_glomeratus',
    name: 'Bushy Bluestem',
    scientificName: 'Andropogon glomeratus',
    family: 'Poaceae',
    nativeRange: 'Americas',
    notes: 'A perennial grass often found in wet, disturbed areas.',
    growthRate: 0.6,
    waterNeed: 0.7,
    tempTolerance: [5, 35],
    hazardResistance: 0.4,
    isPoisonous: false,
    isRare: false
  },
  'anemone_nemorosa': {
    id: 'anemone_nemorosa',
    name: 'Wood Anemone',
    scientificName: 'Anemone nemorosa',
    family: 'Ranunculaceae',
    nativeRange: 'Europe',
    notes: 'A spring-flowering plant that spreads slowly via rhizomes.',
    growthRate: 0.3,
    waterNeed: 0.5,
    tempTolerance: [0, 20],
    hazardResistance: 0.3,
    isPoisonous: true,
    isRare: false
  },
  'angraecum_sesquipedale': {
    id: 'angraecum_sesquipedale',
    name: "Darwin's Orchid",
    scientificName: 'Angraecum sesquipedale',
    family: 'Orchidaceae',
    nativeRange: 'Madagascar',
    notes: 'Famous for its long nectar spur, which predicted a co-evolved moth pollinator.',
    growthRate: 0.05,
    waterNeed: 0.6,
    tempTolerance: [15, 30],
    hazardResistance: 0.4,
    isPoisonous: false,
    isRare: true
  },
  'arabidopsis_thaliana': {
    id: 'arabidopsis_thaliana',
    name: 'Thale Cress',
    scientificName: 'Arabidopsis thaliana',
    family: 'Brassicaceae',
    nativeRange: 'Eurasia & Africa',
    notes: 'A small flowering plant widely used as a model organism in plant biology.',
    growthRate: 0.9,
    waterNeed: 0.4,
    tempTolerance: [5, 30],
    hazardResistance: 0.2,
    isPoisonous: false,
    isRare: false
  },
  'arachis_hypogaea': {
    id: 'arachis_hypogaea',
    name: 'Peanut',
    scientificName: 'Arachis hypogaea',
    family: 'Fabaceae',
    nativeRange: 'South America',
    notes: 'A legume that develops its fruit (peanuts) underground.',
    growthRate: 0.4,
    waterNeed: 0.5,
    tempTolerance: [15, 35],
    hazardResistance: 0.4,
    isPoisonous: false,
    isRare: false,
    nutritionalValue: 0.9
  },
  'argyroxiphium_sandwicense': {
    id: 'argyroxiphium_sandwicense',
    name: 'Haleakalā Silversword',
    scientificName: 'Argyroxiphium sandwicense',
    family: 'Asteraceae',
    nativeRange: 'Hawaii',
    notes: 'A rare, rosette-forming plant found only at high elevations on Maui.',
    growthRate: 0.01,
    waterNeed: 0.2,
    tempTolerance: [-5, 20],
    hazardResistance: 0.6,
    isPoisonous: false,
    isRare: true
  },
  'artemisia_annua': {
    id: 'artemisia_annua',
    name: 'Sweet Wormwood',
    scientificName: 'Artemisia annua',
    family: 'Asteraceae',
    nativeRange: 'Eurasia',
    notes: 'Source of artemisinin, a key compound in anti-malarial drugs.',
    growthRate: 0.5,
    waterNeed: 0.3,
    tempTolerance: [5, 35],
    hazardResistance: 0.6,
    isPoisonous: false,
    isRare: false,
    medicinalValue: 1.0
  },
  'asclepias_syriaca': {
    id: 'asclepias_syriaca',
    name: 'Common Milkweed',
    scientificName: 'Asclepias syriaca',
    family: 'Apocynaceae',
    nativeRange: 'Eastern North America',
    notes: 'A crucial host plant for the larvae of Monarch butterflies.',
    growthRate: 0.4,
    waterNeed: 0.4,
    tempTolerance: [5, 35],
    hazardResistance: 0.5,
    isPoisonous: true,
    isRare: false
  },
  'asparagus_officinalis': {
    id: 'asparagus_officinalis',
    name: 'Asparagus',
    scientificName: 'Asparagus officinalis',
    family: 'Asparagaceae',
    nativeRange: 'Europe & Western Asia',
    notes: 'A perennial vegetable cultivated for its tender young shoots.',
    growthRate: 0.3,
    waterNeed: 0.4,
    tempTolerance: [5, 30],
    hazardResistance: 0.4,
    isPoisonous: false,
    isRare: false,
    nutritionalValue: 0.7
  },
  'astrophytum_asterias': {
    id: 'astrophytum_asterias',
    name: 'Star Cactus',
    scientificName: 'Astrophytum asterias',
    family: 'Cactaceae',
    nativeRange: 'Mexico & Texas',
    notes: 'A small, spineless cactus that is endangered in its natural habitat.',
    growthRate: 0.03,
    waterNeed: 0.05,
    tempTolerance: [10, 45],
    hazardResistance: 0.9,
    isPoisonous: false,
    isRare: true
  },
  'avena_sativa': {
    id: 'avena_sativa',
    name: 'Oat',
    scientificName: 'Avena sativa',
    family: 'Poaceae',
    nativeRange: 'Fertile Crescent',
    notes: 'A cereal grain grown for its seeds, used as food and fodder.',
    growthRate: 0.6,
    waterNeed: 0.4,
    tempTolerance: [0, 30],
    hazardResistance: 0.3,
    isPoisonous: false,
    isRare: false,
    nutritionalValue: 0.8
  },
  'bambusoideae': {
    id: 'bambusoideae',
    name: 'Bamboo',
    scientificName: 'Bambusoideae',
    family: 'Poaceae',
    nativeRange: 'Worldwide (tropical)',
    notes: 'A diverse group of grasses, some of which are the fastest-growing woody plants on Earth.',
    growthRate: 1.0,
    waterNeed: 0.7,
    tempTolerance: [15, 40],
    hazardResistance: 0.5,
    isPoisonous: false,
    isRare: false,
    woodQuality: 0.7
  },
  'bellis_perennis': {
    id: 'bellis_perennis',
    name: 'Common Daisy',
    scientificName: 'Bellis perennis',
    family: 'Asteraceae',
    nativeRange: 'Europe',
    notes: 'A familiar lawn flower that closes its petals at night and opens in the morning.',
    growthRate: 0.5,
    waterNeed: 0.4,
    tempTolerance: [5, 30],
    hazardResistance: 0.2,
    isPoisonous: false,
    isRare: false
  },
  'beta_vulgaris': {
    id: 'beta_vulgaris',
    name: 'Beet',
    scientificName: 'Beta vulgaris',
    family: 'Amaranthaceae',
    nativeRange: 'Mediterranean',
    notes: 'A plant cultivated for its edible taproot (beetroot) and leaves (chard).',
    growthRate: 0.4,
    waterNeed: 0.5,
    tempTolerance: [5, 30],
    hazardResistance: 0.4,
    isPoisonous: false,
    isRare: false,
    nutritionalValue: 0.7
  },
  'bouteloua_gracilis': {
    id: 'bouteloua_gracilis',
    name: 'Blue Grama',
    scientificName: 'Bouteloua gracilis',
    family: 'Poaceae',
    nativeRange: 'North America',
    notes: 'A dominant prairie grass valued for its drought tolerance.',
    growthRate: 0.4,
    waterNeed: 0.1,
    tempTolerance: [-10, 40],
    hazardResistance: 0.8,
    isPoisonous: false,
    isRare: false
  },
  'brassica_oleracea': {
    id: 'brassica_oleracea',
    name: 'Wild Cabbage',
    scientificName: 'Brassica oleracea',
    family: 'Brassicaceae',
    nativeRange: 'Coastal Europe',
    notes: 'A species that has been bred into many common vegetables like broccoli, cauliflower, and kale.',
    growthRate: 0.5,
    waterNeed: 0.5,
    tempTolerance: [5, 25],
    hazardResistance: 0.4,
    isPoisonous: false,
    isRare: false,
    nutritionalValue: 0.8
  },
  'brugmansia_suaveolens': {
    id: 'brugmansia_suaveolens',
    name: "Angel's Trumpet",
    scientificName: 'Brugmansia suaveolens',
    family: 'Solanaceae',
    nativeRange: 'South America',
    notes: 'A large shrub or small tree with pendulous, fragrant flowers that are highly toxic.',
    growthRate: 0.3,
    waterNeed: 0.6,
    tempTolerance: [10, 35],
    hazardResistance: 0.5,
    isPoisonous: true,
    isRare: false
  },
  'caesalpinia_pulcherrima': {
    id: 'caesalpinia_pulcherrima',
    name: 'Peacock Flower',
    scientificName: 'Caesalpinia pulcherrima',
    family: 'Fabaceae',
    nativeRange: 'Tropical Americas',
    notes: 'A showy shrub with red and yellow flowers, often grown as an ornamental.',
    growthRate: 0.4,
    waterNeed: 0.3,
    tempTolerance: [15, 40],
    hazardResistance: 0.6,
    isPoisonous: true,
    isRare: false
  },
  'calamagrostis_acutiflora': {
    id: 'calamagrostis_acutiflora',
    name: 'Feather Reed Grass',
    scientificName: 'Calamagrostis × acutiflora',
    family: 'Poaceae',
    nativeRange: 'Europe & Asia',
    notes: 'A popular ornamental grass with tall, narrow, feathery plumes.',
    growthRate: 0.5,
    waterNeed: 0.4,
    tempTolerance: [0, 35],
    hazardResistance: 0.4,
    isPoisonous: false,
    isRare: false
  },
  'calendula_officinalis': {
    id: 'calendula_officinalis',
    name: 'Pot Marigold',
    scientificName: 'Calendula officinalis',
    family: 'Asteraceae',
    nativeRange: 'Southern Europe',
    notes: 'A flowering plant with edible petals, often used in herbal remedies and salads.',
    growthRate: 0.6,
    waterNeed: 0.4,
    tempTolerance: [5, 30],
    hazardResistance: 0.4,
    isPoisonous: false,
    isRare: false,
    medicinalValue: 0.7,
    nutritionalValue: 0.4
  },
  'camellia_sinensis': {
    id: 'camellia_sinensis',
    name: 'Tea Plant',
    scientificName: 'Camellia sinensis',
    family: 'Theaceae',
    nativeRange: 'East Asia',
    notes: 'The leaves of this shrub are processed to produce the popular beverage, tea.',
    growthRate: 0.2,
    waterNeed: 0.6,
    tempTolerance: [10, 30],
    hazardResistance: 0.4,
    isPoisonous: false,
    isRare: false,
    nutritionalValue: 0.3
  },
  'cannabis_sativa': {
    id: 'cannabis_sativa',
    name: 'Hemp',
    scientificName: 'Cannabis sativa',
    family: 'Cannabaceae',
    nativeRange: 'Central Asia',
    notes: 'A versatile plant cultivated for its fibers, seeds, and psychoactive resins.',
    growthRate: 0.8,
    waterNeed: 0.5,
    tempTolerance: [10, 35],
    hazardResistance: 0.6,
    isPoisonous: false,
    isRare: false,
    woodQuality: 0.4
  },
  'capsicum_annuum': {
    id: 'capsicum_annuum',
    name: 'Bell Pepper',
    scientificName: 'Capsicum annuum',
    family: 'Solanaceae',
    nativeRange: 'Americas',
    notes: 'A species of pepper that includes both sweet bell peppers and spicy chili varieties.',
    growthRate: 0.5,
    waterNeed: 0.6,
    tempTolerance: [15, 35],
    hazardResistance: 0.3,
    isPoisonous: false,
    isRare: false,
    nutritionalValue: 0.8
  },
  'catharanthus_roseus': {
    id: 'catharanthus_roseus',
    name: 'Madagascar Periwinkle',
    scientificName: 'Catharanthus roseus',
    family: 'Apocynaceae',
    nativeRange: 'Madagascar',
    notes: 'A tropical plant containing alkaloids used in chemotherapy drugs.',
    growthRate: 0.4,
    waterNeed: 0.3,
    tempTolerance: [15, 40],
    hazardResistance: 0.7,
    isPoisonous: true,
    isRare: false,
    medicinalValue: 1.0
  },
  'cedrus_libani': {
    id: 'cedrus_libani',
    name: 'Cedar of Lebanon',
    scientificName: 'Cedrus libani',
    family: 'Pinaceae',
    nativeRange: 'Mediterranean',
    notes: 'A majestic, slow-growing conifer known for its fragrant, durable wood.',
    growthRate: 0.05,
    waterNeed: 0.3,
    tempTolerance: [-5, 25],
    hazardResistance: 0.6,
    isPoisonous: false,
    isRare: true,
    woodQuality: 1.0
  },
  'celtis_occidentalis': {
    id: 'celtis_occidentalis',
    name: 'Hackberry',
    scientificName: 'Celtis occidentalis',
    family: 'Cannabaceae',
    nativeRange: 'North America',
    notes: 'A hardy tree commonly planted in urban areas for its tolerance to pollution.',
    growthRate: 0.2,
    waterNeed: 0.4,
    tempTolerance: [-10, 35],
    hazardResistance: 0.8,
    isPoisonous: false,
    isRare: false
  },
  'centaurea_cyanus': {
    id: 'centaurea_cyanus',
    name: 'Cornflower',
    scientificName: 'Centaurea cyanus',
    family: 'Asteraceae',
    nativeRange: 'Europe',
    notes: 'An annual flowering plant with bright blue blossoms, now a symbol for various causes.',
    growthRate: 0.6,
    waterNeed: 0.4,
    tempTolerance: [5, 30],
    hazardResistance: 0.3,
    isPoisonous: false,
    isRare: false
  },
  'ceratonia_siliqua': {
    id: 'ceratonia_siliqua',
    name: 'Carob',
    scientificName: 'Ceratonia siliqua',
    family: 'Fabaceae',
    nativeRange: 'Mediterranean',
    notes: 'An evergreen tree whose pods are used as a chocolate substitute.',
    growthRate: 0.1,
    waterNeed: 0.2,
    tempTolerance: [10, 40],
    hazardResistance: 0.7,
    isPoisonous: false,
    isRare: false,
    nutritionalValue: 0.7
  },
  'chamaemelum_nobile': {
    id: 'chamaemelum_nobile',
    name: 'Roman Chamomile',
    scientificName: 'Chamaemelum nobile',
    family: 'Asteraceae',
    nativeRange: 'Europe & North Africa',
    notes: 'A low-growing plant with daisy-like flowers, used for herbal tea and ground cover.',
    growthRate: 0.5,
    waterNeed: 0.4,
    tempTolerance: [5, 30],
    hazardResistance: 0.4,
    isPoisonous: false,
    isRare: false,
    medicinalValue: 0.6
  },
  'cinnamomum_verum': {
    id: 'cinnamomum_verum',
    name: 'True Cinnamon',
    scientificName: 'Cinnamomum verum',
    family: 'Lauraceae',
    nativeRange: 'Sri Lanka',
    notes: 'An evergreen tree whose inner bark is harvested to produce the spice cinnamon.',
    growthRate: 0.1,
    waterNeed: 0.6,
    tempTolerance: [15, 35],
    hazardResistance: 0.5,
    isPoisonous: false,
    isRare: true,
    medicinalValue: 0.5
  },
  'citrus_sinensis': {
    id: 'citrus_sinensis',
    name: 'Sweet Orange',
    scientificName: 'Citrus × sinensis',
    family: 'Rutaceae',
    nativeRange: 'Southeast Asia',
    notes: 'A hybrid citrus tree widely cultivated for its flavorful fruit.',
    growthRate: 0.15,
    waterNeed: 0.6,
    tempTolerance: [10, 35],
    hazardResistance: 0.4,
    isPoisonous: false,
    isRare: false,
    nutritionalValue: 0.9
  },
  'cocos_nucifera': {
    id: 'cocos_nucifera',
    name: 'Coconut Palm',
    scientificName: 'Cocos nucifera',
    family: 'Arecaceae',
    nativeRange: 'Tropical Pacific',
    notes: 'A versatile palm tree providing food, drink, fiber, and wood, known as the "Tree of Life".',
    growthRate: 0.1,
    waterNeed: 0.8,
    tempTolerance: [20, 45],
    hazardResistance: 0.6,
    isPoisonous: false,
    isRare: false,
    nutritionalValue: 1.0,
    woodQuality: 0.6
  },
  'coffea_arabica': {
    id: 'coffea_arabica',
    name: 'Arabian Coffee',
    scientificName: 'Coffea arabica',
    family: 'Rubiaceae',
    nativeRange: 'Ethiopia',
    notes: 'A shrub whose seeds (beans) are roasted and brewed to make coffee.',
    growthRate: 0.15,
    waterNeed: 0.6,
    tempTolerance: [15, 30],
    hazardResistance: 0.4,
    isPoisonous: false,
    isRare: false,
    nutritionalValue: 0.2
  },
  'colocasia_esculenta': {
    id: 'colocasia_esculenta',
    name: 'Taro',
    scientificName: 'Colocasia esculenta',
    family: 'Araceae',
    nativeRange: 'Southeast Asia',
    notes: 'A tropical plant grown for its starchy corm, a staple food in many Pacific cultures.',
    growthRate: 0.4,
    waterNeed: 0.9,
    tempTolerance: [15, 40],
    hazardResistance: 0.3,
    isPoisonous: false,
    isRare: false,
    nutritionalValue: 0.9
  },
  'convallaria_majalis': {
    id: 'convallaria_majalis',
    name: 'Lily of the Valley',
    scientificName: 'Convallaria majalis',
    family: 'Asparagaceae',
    nativeRange: 'Eurasia',
    notes: 'A fragrant woodland plant, highly poisonous if ingested.',
    growthRate: 0.3,
    waterNeed: 0.5,
    tempTolerance: [0, 25],
    hazardResistance: 0.4,
    isPoisonous: true,
    isRare: false
  },
  'corylus_avellana': {
    id: 'corylus_avellana',
    name: 'Common Hazel',
    scientificName: 'Corylus avellana',
    family: 'Betulaceae',
    nativeRange: 'Europe & Western Asia',
    notes: 'A deciduous shrub valued for its edible nuts (hazelnuts or filberts).',
    growthRate: 0.2,
    waterNeed: 0.5,
    tempTolerance: [5, 30],
    hazardResistance: 0.4,
    isPoisonous: false,
    isRare: false,
    nutritionalValue: 0.8
  },
  'cucumis_sativus': {
    id: 'cucumis_sativus',
    name: 'Cucumber',
    scientificName: 'Cucumis sativus',
    family: 'Cucurbitaceae',
    nativeRange: 'South Asia',
    notes: 'A creeping vine widely grown for its fleshy, edible fruit, used as a vegetable.',
    growthRate: 0.7,
    waterNeed: 0.7,
    tempTolerance: [15, 35],
    hazardResistance: 0.2,
    isPoisonous: false,
    isRare: false,
    nutritionalValue: 0.6
  },
  'cupressus_sempervirens': {
    id: 'cupressus_sempervirens',
    name: 'Mediterranean Cypress',
    scientificName: 'Cupressus sempervirens',
    family: 'Cupressaceae',
    nativeRange: 'Mediterranean',
    notes: 'A narrow, columnar conifer often planted in formal gardens and cemeteries.',
    growthRate: 0.1,
    waterNeed: 0.3,
    tempTolerance: [5, 35],
    hazardResistance: 0.7,
    isPoisonous: false,
    isRare: false,
    woodQuality: 0.8
  },
  'cyclamen_persicum': {
    id: 'cyclamen_persicum',
    name: 'Persian Cyclamen',
    scientificName: 'Cyclamen persicum',
    family: 'Primulaceae',
    nativeRange: 'Mediterranean',
    notes: 'A popular houseplant with upswept, butterfly-like flowers in various colors.',
    growthRate: 0.3,
    waterNeed: 0.4,
    tempTolerance: [10, 25],
    hazardResistance: 0.3,
    isPoisonous: true,
    isRare: false
  },
  'cynodon_dactylon': {
    id: 'cynodon_dactylon',
    name: 'Bermuda Grass',
    scientificName: 'Cynodon dactylon',
    family: 'Africa & Australia',
    nativeRange: 'Africa & Australia',
    notes: 'A tough, aggressive grass species widely used for lawns and pastures.',
    growthRate: 0.8,
    waterNeed: 0.3,
    tempTolerance: [10, 45],
    hazardResistance: 0.6,
    isPoisonous: false,
    isRare: false
  },
  'cynosurus_cristatus': {
    id: 'cynosurus_cristatus',
    name: "Crested Dog's-tail",
    scientificName: 'Cynosurus cristatus',
    family: 'Poaceae',
    nativeRange: 'Europe',
    notes: 'A perennial grass often found in old pastures and hay meadows.',
    growthRate: 0.5,
    waterNeed: 0.4,
    tempTolerance: [5, 30],
    hazardResistance: 0.4,
    isPoisonous: false,
    isRare: false
  },
  'dactylis_glomerata': {
    id: 'dactylis_glomerata',
    name: 'Orchard Grass',
    scientificName: 'Dactylis glomerata',
    family: 'Poaceae',
    nativeRange: 'Eurasia & North Africa',
    notes: 'A common, clumping grass used worldwide for grazing and hay.',
    growthRate: 0.6,
    waterNeed: 0.5,
    tempTolerance: [5, 35],
    hazardResistance: 0.4,
    isPoisonous: false,
    isRare: false
  }
};
